baseURL = "https://alc-beijing.github.io/alc-site"
googleAnalytics = "UA-6539751-3"
languageCode = "en-us"
title = "ALC Beijing"
disableKinds = ["taxonomy", "taxonomyTerm"]
theme = "tale4zh"
canonifyURLs = true



[menu]
  [[menu.main]]
    identifier = "post"
    name = "博客"
    title = "post"
    url = "/post/"
    weight = 0
 [[menu.main]]
    identifier = "about"
    name = "关于 ALC Beijing"
    title = "About"
    url = "/post/alc-beijing-creation/"
    weight = 0
[[menu.main]]
    identifier = "translation"
    name = "翻译"
    title = "Translation"
    url = "https://github.com/alc-beijing/translation"
    weight = 0
